### ISSUE TITLE
The code in the Marketplace is not the latest, causing the extension unworkable

### ISSUE THREAD

**Issue by hakula139** [TheNetAdmin/vscode-linkerscript#2]
Though the incorrect path issue of package.json was fixed (#1) in the source code, it seems that the extension published in the [VS Code Extension Marketplace](https://marketplace.visualstudio.com/items?itemName=ZixuanWang.linkerscript) has not been synchronized with the code here, so it is currently unworkable. Maybe you can update it when you have time. Many thanks!

**Comment by TheNetAdmin** [comment]
Oh I forgot that, will do soon

**Comment by TheNetAdmin** [comment]
I just [publish the version `v1.0.1`](https://github.com/TheNetAdmin/vscode-linkerscript/runs/835745054?check_suite_focus=true) to vscode marketplace. It should be available in a few minutes.

**Comment by TheNetAdmin** [comment]
This plugin is updated in vscode marketplace and available for vscode client to download.

I'm closing this issue and please open a new issue if there are other problems.
