### ISSUE TITLE
Publish to https://open-vsx.org/ for VSCodium

### ISSUE THREAD

**Issue by ad7718** [TheNetAdmin/vscode-linkerscript#3]
It will be good if this extension will be also available in open-vsx repository.

**Comment by TheNetAdmin** [comment]
Interesting. Wasn't aware of the publication process for vscodium.

I'll try it later this week.

**Comment by TheNetAdmin** [comment]
It's published on open-vsx now:

https://open-vsx.org/extension/ZixuanWang/linkerscript

**Comment by ad7718** [comment]
Thank you!
