### ISSUE TITLE
"/*" in "Input Section Wildcard Patterns" recognized as "Comment" beginning

### ISSUE THREAD

**Issue by philgekni** [TheNetAdmin/vscode-linkerscript#6]
Hi,
I encounter the following issue with an input filename (within an ["Input Selection Description"](https://sourceware.org/binutils/docs/ld/Input-Section-Basics.html)) using wildcards when "/\*" is present:
![linker-script-plugin-wrong-comment-highlighting](https://user-images.githubusercontent.com/29202864/215605784-6af9fe70-857f-48d7-99f8-9fb3ae2f6c01.PNG)
As shown, the "/\*", in the middle of the filename, is incorrectly interpreted as a comment delimiter.

Apparently a related problem have been already [encountered by ld developers](https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=ld/ldlex.l;h=cf596530b2029e485cde648fac5068c3ca91d2b2;hb=HEAD#l417). If I correctly understood, the text should be considered as a comment only if the token begin with "/\*" (so, in my example, if the _filename_ was beginning with "/\*").

**Comment by Icedude907** [comment]
Fixed?

**Comment by TheNetAdmin** [comment]
> Fixed?

You are right, I forgot to close this issue
